package one.reevdev.stood.features.common.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class StoodColors(
    // Primary colors
    val surface: Color,
    val surfaceDim: Color,
    val surfaceBright: Color,
    val surfaceContainerLowest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val onSurface: Color,
    val outline: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    // Accent colors
    val eggShell: Color,
    val burntSienna: Color,
    val delftBlue: Color,
    val cambridgeBlue: Color,
    val sunset: Color,
    val onEggShell: Color,
    val onBurntSienna: Color,
    val onDelftBlue: Color,
    val onCambridgeBlue: Color,
    val onSunset: Color,
    // Text colors
    val textColor: Color,
    val textDisabled: Color,
    // State colors
    val primaryUnfocused: Color,
    val primaryFocused: Color,
)


val LocalLightStoodColors = staticCompositionLocalOf {
    StoodColors(
        surface = lightSurface,
        surfaceDim = lightSurfaceDim,
        surfaceBright = lightSurfaceBright,
        surfaceContainerLowest = lightSurfaceContainerLowest,
        surfaceContainerLow = lightSurfaceContainerLow,
        surfaceContainer = lightSurfaceContainer,
        surfaceContainerHigh = lightSurfaceContainerHigh,
        surfaceContainerHighest = lightSurfaceContainerHighest,
        onSurface = lightOnSurface,
        outline = lightOutline,
        surfaceVariant = lightSurfaceVariant,
        onSurfaceVariant = lightOnSurfaceVariant,
        primary = lightPrimary,
        onPrimary = lightOnPrimary,
        primaryContainer = lightPrimaryContainer,
        onPrimaryContainer = lightOnPrimaryContainer,
        secondary = lightSecondary,
        onSecondary = lightOnSecondary,
        secondaryContainer = lightSecondaryContainer,
        onSecondaryContainer = lightOnSecondaryContainer,
        tertiary = lightTertiary,
        onTertiary = lightOnTertiary,
        tertiaryContainer = lightTertiaryContainer,
        onTertiaryContainer = lightOnTertiaryContainer,
        error = lightError,
        onError = lightOnError,
        errorContainer = lightErrorContainer,
        onErrorContainer = lightOnErrorContainer,
        eggShell = lightEggShell,
        burntSienna = lightBurntSienna,
        delftBlue = lightDelftBlue,
        cambridgeBlue = lightCambridgeBlue,
        sunset = lightSunset,
        onEggShell = lightEggShell,
        onBurntSienna = lightBurntSienna,
        onDelftBlue = lightDelftBlue,
        onCambridgeBlue = lightCambridgeBlue,
        onSunset = lightSunset,
        textColor = lightTextColor,
        textDisabled = lightTextDisabled,
        primaryUnfocused = lightPrimaryUnfocused,
        primaryFocused = lightPrimaryFocused
    )
}

val LocalDarkStoodColors = staticCompositionLocalOf {
    StoodColors(
        surface = darkSurface,
        surfaceDim = darkSurfaceDim,
        surfaceBright = darkSurfaceBright,
        surfaceContainerLowest = darkSurfaceContainerLowest,
        surfaceContainerLow = darkSurfaceContainerLow,
        surfaceContainer = darkSurfaceContainer,
        surfaceContainerHigh = darkSurfaceContainerHigh,
        surfaceContainerHighest = darkSurfaceContainerHighest,
        onSurface = darkOnSurface,
        outline = darkOutline,
        surfaceVariant = darkSurfaceVariant,
        onSurfaceVariant = darkOnSurfaceVariant,
        primary = darkPrimary,
        onPrimary = darkOnPrimary,
        primaryContainer = darkPrimaryContainer,
        onPrimaryContainer = darkOnPrimaryContainer,
        secondary = darkSecondary,
        onSecondary = darkOnSecondary,
        secondaryContainer = darkSecondaryContainer,
        onSecondaryContainer = darkOnSecondaryContainer,
        tertiary = darkTertiary,
        onTertiary = darkOnTertiary,
        tertiaryContainer = darkTertiaryContainer,
        onTertiaryContainer = darkOnTertiaryContainer,
        error = darkError,
        onError = darkOnError,
        errorContainer = darkErrorContainer,
        onErrorContainer = darkOnErrorContainer,
        eggShell = darkEggShell,
        burntSienna = darkBurntSienna,
        delftBlue = darkDelftBlue,
        cambridgeBlue = darkCambridgeBlue,
        sunset = darkSunset,
        onEggShell = darkEggShell,
        onBurntSienna = darkBurntSienna,
        onDelftBlue = darkDelftBlue,
        onCambridgeBlue = darkCambridgeBlue,
        onSunset = darkSunset,
        textColor = darkTextColor,
        textDisabled = darkTextDisabled,
        primaryUnfocused = darkPrimaryUnfocused,
        primaryFocused = darkPrimaryFocused
    )
}